[package]
name = "minimuxer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_libimobiledevice = { version = "0.1", features = ["dynamic"], default-features = false }
plist_plus = { version = "0.2", features = ["dynamic"] }

libc = "0.2"
simplelog = "0.12"
log = "*"

reqwest = { version = "0.11", features = ["blocking"] }
serde = "1.0"
serde_json = "1.0"
zip = "0.6"
plist = "1"
num_enum = "0"

[build-dependencies]
cbindgen = "0.20"

[profile.release]
panic = "abort"

[lib]
crate-type = ["staticlib", "rlib"]
